version: "3"
services:
  angularfrontend:
    image: maddob/blog_frontend_nginx:latest
    ports:
      - 4200:80
    networks:
      - webnet

  springbootbackend:
    image: maddob/blog_backend_docker_compose:0.3.8
    container_name: blogbackend
    ports:
      - 8000:8000
    networks:
      - webnet

  keycloak:
    container_name: keycloak
    volumes:
      - /Users/martin/Workspaces/NB/Playground/blog/src/main/resources/keycloak/Demo-realm.json:/tmp/Demo-realm.json
    image: jboss/keycloak:8.0.1
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/Demo-realm.json
    ports:
      - 8080:8080
    networks:
      - webnet
networks:
  webnet: