version: "3.9"
services:
  frontend:
    image: maddob/blog-frontend:0.1.1
    container_name: blogfrontend
    ports:
      - '4200:80'
    volumes:
      - /Users/martindobrev/Workspaces/Akros/madblog-backend-springboot/src/main/resources/nginx/templates/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - KEYCLOAK_HOST="keycloak:8080"
      - BLOG_BACKEND_HOST="blogbackend:8000"
      - TEST_HOST="78.83.86.98:4200"
    depends_on:
      - backend
      - keycloak

  backend:
    image: maddob/blog-backend:0.3.9
    container_name: blogbackend
    ports:
      - '8000:8000'
    environment:
      - BLOG_SECURITY_DISABLED=false
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
#    depends_on:
#      - keycloak

  keycloak:
    container_name: keycloak
    volumes:
      - /Users/martindobrev/Workspaces/Akros/madblog-backend-springboot/src/main/resources/keycloak/Demo-realm.json:/tmp/Demo-realm.json
    image: jboss/keycloak:16.1.1
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://localhost:8080/auth
      - KEYCLOAK_IMPORT=/tmp/Demo-realm.json
    ports:
      - '8080:8080'
